theme: jekyll-theme-slate
title: GEARS | 齿轮组
tagline: Geant4 Example Application with Rich features yet Small footprint
show_downloads: true
github:
  zip_url: https://github.com/jintonic/gears/zipball/master
  tar_url: https://github.com/jintonic/gears/tarball/master
  
plugins:
  - jekyll-mentions
  - jekyll-seo-tag

# the slate theme already contains the script to use this id
google_analytics: UA-61659360-3
