/control/verbose 2
/geometry/source concrete.tg

/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree

/geometry/test/run

/vis/open HepRepFile
/vis/drawVolume

/gps/particle neutron
/gps/ene/type Gauss
/gps/ene/mono 400 MeV
/gps/ene/sigma 10 MeV
/gps/direction 0 0 1

/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 100

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow

/tracking/verbose 2
/run/beamOn 10

/vis/disable
/tracking/verbose 0
/analysis/setFileName n400MeVinConcrete.root
/run/verbose 2
/run/printProgress 1000
/run/beamOn 10000

