/control/verbose 2
/geometry/source NA.tg

/run/initialize

/vis/ASCIITree/verbose 13
/vis/drawTree

/geometry/test/run

/vis/open HepRepFile
/vis/drawVolume
/vis/scene/add/axes 0 0 0 1 m
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate 100
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set neutron yellow

/gps/particle neutron
/gps/ene/type Gauss
/gps/ene/mono 1 MeV
/gps/ene/sigma 10 MeV
/gps/direction 0 0 1

/tracking/verbose 2
/run/beamOn 1

#/vis/disable
#/tracking/verbose 0
#/analysis/setFileName n400MeVinConcrete.root
#/run/verbose 2
#/run/printProgress 1000
#/run/beamOn 10000

